id: P001690
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:14:53.946195
source_metadata:
  id: bdr:W3817
  title: ལམ་རིམ་རྣམ་གྲོལ་ལག་བཅངས། （ལྷ་ས་པར་མ།）
  author: ''
  volumes:
    8a4e0eee825d4c48920e5b6f85a2ee6e:
      image_group_id: I1KG540
      title: ''
      volume_number: 1
      total_pages: 784
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
