id: IFE0E1464
legacy_id: P001690
ocr_import_info:
  bdrc_scan_id: W3817
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T06:09:10'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T12:06:49.343000+00:00'
last_modified: 2022-09-03 20:07:34.487321
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3817
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3817
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལམ་རིམ་རྣམ་གྲོལ་ལག་བཅངས། （ལྷ་ས་པར་མ།）
  author: ཁྲི་བྱང ༠༣་བློ་བཟང་ཡེ་ཤེས་བསྟན་འཛིན་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.520601585599351
  ocr_word_median_confidence_index: 0.4699999988079071
quality: null
bases:
  I1KG540:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG540
      total_pages: 784
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG540.txt
    statistics:
      ocr_word_median_confidence_index: 0.4699999988079071
      ocr_word_mean_confidence_index: 0.520601585599351
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
