id: IFE0E1464
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T06:11:02+00:00'
last_modified: '2022-06-07T14:02:10.124437+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3817
  title: ལམ་རིམ་རྣམ་གྲོལ་ལག་བཅངས། （ལྷ་ས་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BF1B:
      image_group_id: I1KG540
      title: ''
      total_pages: 784
      order: 1
      base_file: BF1B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
